name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  run-workflow:
    name: Run workflow
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Restore cached dependencies
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Lint
        run: |
          npx eslint src --ext .js,.jsx,.ts,.tsx --fix

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v6
